function Comp = addComponents2Panel2_Date(hPanel)


ColumnName =  [];
RowName = [];

h_TB = 0.9;
y_TB = 1-h_TB;
Comp.Table.Date = uitable('parent', hPanel,...
                                           'Units', 'normalized', ...
                                           'Position', [0 y_TB 1 h_TB],...
                                             'ForegroundColor',         [1 1 1],...
                                            'BackgroundColor',         [0 0 0],...
                                            'ColumnName',               ColumnName,...
                                            'Columnwidth',                {30 200 50},...
                                            'ColumnFormat',             {'logical', 'char', 'char'},...
                                            'ColumnEditable',            [true false false], ...
                                            'RowName',                     RowName, ...
                                            'FontSize',                       10, ....
                                            'CellSelectionCallback',    @Callback2_Table_DatePanel_Date);

gap = 0.05;
nPB = 2;
w_PB = (1-gap*(nPB+1))/nPB;
h_PB = 0.06;
y_PB = (y_TB-h_PB)/2;

BC_PB = [1 1 1]*0.25;
FS = 12;


Comp.Pushbutton.ImgSet1 = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Image Set 1',...
                                'Unit', 'Normalized',...
                                'Position', [gap y_PB w_PB h_PB],...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Tag', 'ImgSet1', ...
                                'Callback', @Callback_Pushbutton_DatePanel_ImageSet);
                            
Comp.Pushbutton.ImgSet2 = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Image Set 2',...
                                'Unit', 'Normalized',...
                                'Position', [gap*2+w_PB y_PB w_PB h_PB],...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Tag', 'ImgSet2', ...
                                'Callback', @Callback_Pushbutton_DatePanel_ImageSet);