function Comp = addComponents2Panel2_Date(hPanel)


ColumnName =  [];
RowName = [];

Comp.Table.Date = uitable('parent', hPanel,...
                                           'Units', 'normalized', ...
                                           'Position', [0 0 1 1],...
                                             'ForegroundColor',         [1 1 1],...
                                            'BackgroundColor',         [0 0 0],...
                                            'ColumnName',               ColumnName,...
                                            'Columnwidth',                {30 200 50},...
                                            'ColumnFormat',             {'logical', 'char', 'char'},...
                                            'ColumnEditable',            [true false false], ...
                                            'RowName',                     RowName,...
                                            'FontSize',                       10);%,....
                                           % 'CellSelectionCallback',    @hTable_SS_Callback);