 function Comp = addComponents2Panel_Patient(hPanel)

h_Gap = 0.05; 
nB = 2;
h_Button = (1-h_Gap*(nB+2))/nB;

BC_PB = [1 1 1]*0.25;
FS = 10;

% patient button
h = 1-h_Gap-h_Button;
Comp.Pushbutton.Patient = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Patient',...
                                'Unit', 'Normalized',...
                                'Position', [0.15 h 0.7 h_Button], ...
                                'FontSize', 12, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_PatientPanel_Patient);
                            
% image info
h = h-h_Gap-h_Button;
Comp.Pushbutton.ImgInfo = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'Image Info',...
                                'Unit', 'Normalized',...
                                'Position', [0.15 h 0.7 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'on', ...
                                'Callback', @Callback_Pushbutton_PatientPanel_ImgInfo);