function Comp = addComponents2Panel2_Gate(hPanel)


ColumnName =  [];
RowName = [];

Comp.Table.Gate = uitable('parent', hPanel,...
                                           'Units', 'normalized', ...
                                           'Position', [0 0 1 1],...
                                             'ForegroundColor',         [1 1 1],...
                                            'BackgroundColor',         [0 0 0],...
                                            'ColumnName',               ColumnName,...
                                            'Columnwidth',                {30 200 50},...
                                            'ColumnFormat',             {'logical', 'char', 'char'},...
                                            'ColumnEditable',            [true false false], ...
                                            'RowName',                     RowName, ...
                                            'FontSize',                       10, ....
                                            'CellSelectionCallback',    @Callback2_GatePanel_GateTable);