 function Comp = addComponents2Panel_Struct(hPanel)

h_Gap = 0.05; 
nB = 5;
h_Button = (1-h_Gap*(nB+2))/nB;

BC_PB = [1 1 1]*0.25;
FS = 12;

% patient button
h = 1-h_Gap-h_Button;
Comp.Pushbutton.List = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'List',...
                                'Unit', 'Normalized',...
                                'Position', [0.15 h 0.7 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Callback', @Callback_Pushbutton_StructPanel_List);
                            
% image info
h = h-h_Gap-h_Button;
Comp.Pushbutton.xxx = uicontrol('parent', hPanel, ...
                                'Style', 'pushbutton',...
                                'String', 'xxx',...
                                'Unit', 'Normalized',...
                                'Position', [0.15 h 0.7 h_Button], ...
                                'FontSize', FS, ...
                                'FontWeight', 'bold', ...
                                'BackgroundColor', BC_PB,...
                                'ForegroundColor', 'c',...
                                'Visible', 'on', ...
                                'Enable', 'off', ...
                                'Callback', @Callback_Pushbutton_PatientPanel_ImgInfo);