function Panel = addPanel(hFig)

h_Patient = 0.1;
h_Img1 = 0.1;
h_Img2 = 0.1;
h_Gate = 0.1;

w_Left = 0.15;
w_Right = 0.0;
w_Middle = 1-w_Right-w_Left;

h_ContrastBar = 0.03;
h_View = 1-h_ContrastBar*2;

%% Load image
y = 1-h_Patient;
Panel.Patient.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y, w_Left, h_Patient], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% Image 1
y = y-h_Img1;
Panel.Img1.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y, w_Left, h_Img1], ...
                                'Title', 'Image Set 1',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% Image 2
y = y-h_Img2;
Panel.Img2.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y, w_Left, h_Img2], ...
                                'Title', 'Image Set 2',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% Gate
y = y-h_Gate;
Panel.Gate.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [0, y, w_Left, h_Img2], ...
                                'Title', 'Gate',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'w',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% View
Panel.AxialView.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Left, 0, w_Middle, h_View], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

%% Contrast bar
Panel.ContrastBar1.hPanel = uipanel('parent', hFig,...
                                'Unit', 'Normalized',...
                                'Position', [w_Left, h_View, w_Middle, h_ContrastBar], ...
                                'Title', '',...
                                'FontSize',                 12,...
                                'Units',                     'normalized', ...
                                'visible',                      'on', ...
                                'ForegroundColor',       'k',...
                                'BackgroundColor',       'k', ...
                                'HighlightColor',          'c',...
                                'ShadowColor',            'k');

% %% Slice slider
% Panel.SliceSlider.hPanel = uipanel('Parent',                    hFig,...    
%                                 'Title',                        '',...
%                                 'FontSize',                 12,...
%                                 'Units',                     'normalized', ...
%                                 'Position',                  [w_Left+w_Middle, 0, w_Right, 1],...
%                                     'visible',                      'on', ...
%                                 'ForegroundColor',       'w',...
%                                 'BackgroundColor',       'black', ...
%                                 'HighlightColor',          'c',...
%                                 'ShadowColor',            'black');
% 
% %% point
% Panel.Point.hPanel = uipanel('parent', hFig,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0, h_About, w_Left, h_Point], ...
%                                 'Title', 'Point on Diaphragm',...
%                                 'FontSize',                 12,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'w',...
%                                 'BackgroundColor',       'k', ...
%                                 'HighlightColor',          'c',...
%                                 'ShadowColor',            'k');
%                             
% %% about
% Panel.About.hPanel = uipanel('parent', hFig,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0, 0., w_Left, h_About], ...
%                                 'Title', '',...
%                                 'FontSize',                 12,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'on', ...
%                                 'ForegroundColor',       'w',...
%                                 'BackgroundColor',       'k', ...
%                                 'HighlightColor',          'k',...
%                                 'ShadowColor',            'k');
%                             
%                             
% %% %%%%%%%%%%%%%%%%% profile
% Panel.Tumor.hPanel = uipanel('parent', hFig,...
%                                 'Unit', 'Normalized',...
%                                 'Position', [0, h_About+h_Point+h_Snake, w_Left, h_Tumor], ...
%                                 'Title', 'Tumor Profile',...
%                                 'FontSize',                 12,...
%                                 'Units',                     'normalized', ...
%                                 'visible',                      'off', ...
%                                 'ForegroundColor',       'w',...
%                                 'BackgroundColor',       'k', ...
%                                 'HighlightColor',          'c',...
%                                 'ShadowColor',            'k');
%                             
% 
% 
